### ISSUE TITLE
MasonryInfiniteGrid: responsive columns with percent width?

### ISSUE THREAD

**Issue by nimmolo** [naver/egjs-infinitegrid#464]
I know it is possible to define column size in px, and then there will be as many columns as possible will fit in container. 

But is it possible to define column size in % and set a different number of columns for different screen width?

I'm thinking of the way bootstrap flex columns (the layout effect, not the CSS).  MasonryIG uses absolute position so implementation is different, but i'd like to get responsive percentage based column effect. (something like `col-12 col-md-6 col-lg-4 col-xxl-3`)

Currently i'm using something like `percentage={true}` and `column={3}`. Maybe param would be `column={{0: 1, 460: 2, 998: 3, 1200: 4}}`

**Comment by nimmolo** [comment]
I'm reading trough `MasonryInfiniteGrid` options again. I'm noticing it seems like maybe i can set `column={0}` so it will calculate columns from width of first element. 

@daybrush - Can MasonryInfiniteGrid use a percentage value for width of first element? If so i could just use Bootstrap responsive column classes on the first element. 

Using those Bootstrap column classes, my item elements have 
```
flex: 0 0 auto;
width: 100%;
@(min-width: 768px) width: 50%;
@(min-width: 992px) width: 33.3333333%;
@(min-width: 1400px) width: 25%;
```

But this is still giving "incorrect" column with calculations - MIG is calculating 3 columns instead of 4, 2 instead of 3, etc., with large gaps. The elements do have the correct widths, but the inline positions for the three columns are `left: 0%;` `left: 37.4844%;` and `left: 74.9689%;` which leaves big gaps, where it seems it should be `left: 0;` `left: 25%` `left:50%;` `left:75%`

![Screen Shot 2022-01-07 at 5 15 30 PM](https://user-images.githubusercontent.com/1948095/148625681-27683482-0709-469f-91b9-97148057c8ab.png)

**Comment by nimmolo** [comment]
Hmm - what is the difference between `isEqualSize` and `isConstantSize`? In the documentation it sounds the same. But when I use in a layout,`isEqualSize` seems to mean **width and height** of all items is the same. Maybe `isConstantSize` means only the **width** is the same?

If i use `isConstantSize={true}`, the first batch of items still 3-column position as above, but the second batch of added elements comes in with the desired 4-column position. Very unexpected! 

Like this:
![Screen Shot 2022-01-07 at 8 31 05 PM](https://user-images.githubusercontent.com/1948095/148631476-3c827faa-5365-48df-93b7-2d101fbf7809.png)
![Screen Shot 2022-01-07 at 8 31 15 PM](https://user-images.githubusercontent.com/1948095/148631479-4f87d2f2-2f01-4cf6-8007-d7301795b333.png)

**Comment by daybrush** [comment]
@nimmolo 

Since the `column` can be changed dynamically, it must be changed programmatically according to its size.

`isConstantSize` does not change the size of the item anymore even if it is resized.

`isEqualSize` means that all items have the same size.

The above problem will be fixed in the next version.

**Comment by nimmolo** [comment]
@daybrush  - I see, Ok, no problem. Maybe should I wait for next version, and work on other things...

But IG does calculate column size correctly for the second load 🤔 (last image above). Why do you think IG can correctly calculate column size on the **reload** load of data, but incorrect on first load? Is there a way I can help pass that calculation of column size programatically to IG so it can calculate first load correctly?

**Comment by daybrush** [comment]
@nimmolo 

The reason is not well understood, but I think it is a decimal point issue. Here is the code to fix this problem in the next version

**Comment by daybrush** [comment]
@nimmolo 

Test @egjs/svelte-infinitegrid@4.1.2-beta.4 (beta) version. Thank you :)

**Comment by nimmolo** [comment]
Thanks @daybrush - I updated to @egjs/svelte-infinitegrid@4.1.2-beta.4.

Issue is still present, sorry. It seems that the first calculation of column width is maybe a little narrower, but... still wrong number of columns on load. On reload, the number of columns is again suddenly correct, but position is unpredictable. First load does not re-layout, so there are two areas with different columns.

There's another issue with both beta.3 and beta.4 (I did not mention before, sorry, but maybe relevant). When I scroll to the `loading` div, the screen and scroll bar "flickers" very fast, and nothing loads. I must scroll backwards and forwards to `loading` several times to load the new batch. 

To help with troubleshooting i can include my most recent code. Let me know if there is anything else I can do to help. 

Here is the Svelte template currently:
```svelte
  <MasonryInfiniteGrid
    class="row ig"
    useLoading={true}
    useFirstRender={true}
    gap={0}
    percentage={true}
    column={0}
    items={newItems}
    itemBy={(item) => item.cursor}
    bind:this={ig}
    on:requestAppend={({ detail: e }) => {
      e.wait();
      handleNext();
      e.ready();
      if (newItems.length && pageInfo.hasPreviousPage) {
        items = [...items, ...newItems];
      }
    }}
    let:visibleItems
>
{#each visibleItems as item (item.key)}
  <Item edge={item.data} />
{/each}
</MasonryInfiniteGrid>
{/if}
```

Here is the CSS, standard Bootstrap 5.1 row and column layout, nothing special.
```css
.row {
  --bs-gutter-x: 1.25rem;
  --bs-gutter-y: 0;
  display: flex;
  flex-wrap: wrap;
  margin-top: calc(-1 * var(--bs-gutter-y));
  margin-right: calc(-0.5 * var(--bs-gutter-x));
  margin-left: calc(-0.5 * var(--bs-gutter-x));
}
.row > * {
  flex-shrink: 0;
  width: 100%;
  max-width: 100%;
  padding-right: calc(var(--bs-gutter-x) * 0.5);
  padding-left: calc(var(--bs-gutter-x) * 0.5);
  margin-top: var(--bs-gutter-y);
}
.col-12 {
  flex: 0 0 auto;
  width: 100%;
}
@(min-width: 768px) {
  .col-md-6 {
    flex: 0 0 auto;
    width: 50%;
  }
}
@(min-width: 992px) {
  .col-lg-4 {
    flex: 0 0 auto;
    width: 33.33333333%;
  }
}
@(min-width: 1400px) {
  .col-xxl-3 {
    flex: 0 0 auto;
    width: 25%;
  }
}
.ig {
  height: 600px; // initial height, gets overwritten
}
```
