### ISSUE TITLE
Svelte getting started example not wokring

### ISSUE THREAD

**Issue by neckaros** [naver/egjs-infinitegrid#468]
## Description
I just copied the code from the [getting started](https://naver.github.io/egjs-infinitegrid/docs/quick-start) in a codesandbox but on load no items appear.
To see items i have to resize the window. Same to see the appended items i have to resize again (on v4.1.1 on v4.2 beta5 the append seems to work by itself)

## Steps to check or reproduce
https://codesandbox.io/s/sveltegridneedresize-forked-iix4x

**Comment by daybrush** [comment]
@neckaros 

Thanks for reporting. I'll check.

**Comment by daybrush** [comment]
@neckaros 
I'm going to fix that bug and temporarily try the following CSS:

```css
:global(body),
:global(html) {
	margin: 0;
	padding: 0;
	position: relative;
	height: 100%;
}
```
